hl.on("hyprland.start", function()
	hl.exec_cmd("vesktop", { workspace = "2 silent", float = true, size = { 1503, 831 }, move = { 400, 234 } })
	hl.exec_cmd("Telegram", { workspace = "2 silent", float = true, size = { 380, 504 }, move = { 12, 307 } })
	hl.exec_cmd("kitty --hold /home/senku/.local/bin/prime", { workspace = "special:magic silent" })
	hl.exec_cmd("zen-browser", { workspace = "1" })
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("quickshell")
	hl.exec_cmd("sleep 10 && bongocat -c ~/.config/bongocat/bongocat.conf")
	-- hl.exec_cmd("")
	-- hl.exec_cmd("")
	-- hl.exec_cmd("nm-applet")
	-- hl.exec_cmd("waybar & hyprpaper & firefox")
end)
