[config.wallpaper]
command = "swww img --transition-type center {{ image }}"
set = true

[templates.waybar]
input_path = '~/.config/matugen/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = 'rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.kitty]
input_path = 'kitty.conf'
output_path = '~/.config/kitty/theme/matugen-theme.conf'
post_hook = "pkill -SIGUSR1 kitty"

[templates.hyprland]
input_path = 'hyprland.conf'
output_path = '~/.config/hypr/themes/colors.conf'
post_hook = 'hyprctl reload'
