general {
    lock_cmd          = ~/.local/bin/lock-pc.sh
    before_sleep_cmd  = loginctl lock-session                                            # lock before system suspends
    after_sleep_cmd   = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "enable" }))'   # turn on display after wake
}

# Dimming the Backlight
listener {
    timeout           = 150                       # 2.5 minutes
    on-timeout        = brightnessctl -s set 10   # save current brightness and drop to 10%
    on-resume         = brightnessctl -r          # restore saved brightness
}

# Turning Off Displays (DPMS)
listener {
    timeout           = 330                       # 5.5 minutes
    on-timeout        = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "disable" }))'
    on-resume         = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "enable" }))'
}

# lock the computer
listener {
    timeout           = 600                       # 10 minutes
    on-timeout        = ~/.local/bin/lock-pc.sh
}

