[opener]
zathura = [
  { run = 'zathura %s', orphan = true, desc = "Open in Zathura" },
]
extract = [
  { run = '''for f in %s; do 7z x -y "$f"; done''', desc = "Extract here (7z)" },
]
live-wallpaper = [
  { run = 'live-wall -s %s', orphan = true, desc = "Set live wallpaper" },
]

[open]
prepend_rules = [
  { url = "*.cbz", use = ["zathura", "extract"] },
  { url = "*.cbr", use = ["zathura", "extract"] },
  { mime = "video/*", use = ["play", "reveal", "live-wallpaper"] },
]
