
# The 10th workplace is a scrolling layout (niri like)
workspace = 10, layout:scrolling

# Use 3-finger horizontal swipes to move focus between columns
gesture = 3, right, dispatcher, layoutmsg, move -col
gesture = 3, left, dispatcher, layoutmsg, move +col

# Use modifier + 3-finger swipe to move the window itself
gesture = 3, right, mod:SHIFT, dispatcher, layoutmsg, swapcol r
gesture = 3, left, mod:SHIFT, dispatcher, layoutmsg, swapcol l

scrolling {
    column_width = 0.75
    fullscreen_on_one_column = false
    direction = right
}
